### PR TITLE
Repl

### PR DESCRIPTION
**Pull request by mikeheft**
Would you mind taking a look. I know there's a lot of class extraction and other refactoring to do. Working on green first, then all of that. 💪 

@s-espinosa

@ali.schlereth

### CODE REVIEW

**Comment by mikeheft** [comment]
@AliSchlereth
Hopefully, that works, lol.

**Comment by s-espinosa** [comment]
@mikeyduece Generally it seems like you're making good progress. Really like all of the work that you've put in on this. It looks nice and it's fun to play. It seems like something is off regarding how hits/misses are being calculated on the Computer Board? See image below.

screen shot 2017-07-17 at 6 27 19 pm

Would like to hear a little bit more from you regarding what specifically you'd like us to look at. I think you're right that some of this could be refactored. Initial thought is that there's a lot of duplication in different places around the board, and I'm thinking that could be extracted to a Board class, but think you're right that you should aim to get from red to green first. Really like how you're using the runner methods to be in charge of lower level, more detailed methods. Think that one other thing you might consider is walking through how you name things to see if you can make it especially clear what each piece is doing. In the same vein would be taking a look at your conditionals to see if you can write them in a way that you don't need a leading `!`. That's usually an indicator that there's a way you could make the logic more straightforward.

Let us know if you have any specific questions!

**Comment by s-espinosa** [comment]
@mikeyduece One other note, had to install a gem to make this run. Table something? If you're going to have a gem like that, make a Gemfile so that people can install those dependencies by just running `bundle`. 👍

**Comment by mikeheft** [comment]
That's what I was looking for, just a quick once over to get feedback on anything that jumps out at you. That and to fulfill some of the rubrik criteria.  But talking to Ali and doing this, it's like why didn't I do this sooner on other projects, haha. I will definitely fix the issues you brought up and I'll look into Gemfiles. Thank you for taking the time to give this a quick look 😎

**Comment by AliSchlereth** [comment]
I encourage you to tag us again if you have any specific questions or once you apply some of the above mentioned refactoring.

**Comment by mikeheft** [comment]
Will do. I always knew on one side that you are resources for our projects, but on the other I really can't understand why I didn't realize and take advantage of it sooner, haha. Thank you again for taking the time to check this out :D

**Pull request merged**
